const projects = [
  {
    id: 'project3',
    title: 'Inventaris',
    img: '/project3/project3.webp',
    link: '/projects/project3',
    date: '2026',
    liveLink: 'https://github.com/Malikkun09/pkl-crud-laravel-2',
    company: 'PKL',
    primary: '#2D2D2D',
    accentColor: '#FCFBF7',
    secondary: '#F2EEE7',
    fillColor: '#F2F3F4',
    menuColor: 'gold',
    menuFontColor: '#2D2D2D',
    fluidColor: '#0028FF',
    images: [
      {
        src: '/project3/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/5.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project3/8.webp',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project3/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/3.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Sistem Inventaris Barang for my PKL: a Laravel 13 inventory app with role-based access, stock ledgers, activity logs, and a security audit that closed injection and session issues.',
      'Four access levels — Super Admin, Admin, Staff Gudang, Viewer — keep stock movements accountable. Forty-six regression tests stay green on shared hosting.',
      'Built with PHP 8.3, Blade, AdminLTE 3, and MySQL. Source is public on GitHub.',
    ],
  },
  {
    id: 'project4',
    title: 'SkillMatch',
    img: '/project4/project4.webp',
    link: '/projects/project4',
    date: '2026',
    company: 'Coding Camp',
    liveLink: 'https://skillmatch.malikfajar.me',
    primary: '#263745',
    accentColor: '#f0f4f1',
    secondary: '#F3F5F7',
    fillColor: '#E0DFFC',
    menuColor: '#5C58EB',
    menuFontColor: '#f0f4f1',
    fluidColor: '#A3A714',
    images: [
      {
        src: '/project4/video.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project4/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/2.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/3.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/4.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/5.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/6.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/7.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/8.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/9.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/10.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/11.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'KerjaIn / SkillMatch is a web platform that helps SMK students find internships, jobs, and career information in one place.',
      'Capstone for Coding Camp 2026 (DBS Foundation): Bridge Your Skills, under the Future-Ready Work & Economy theme.',
      'Profiles, opportunity search, and a clean interface built so students can actually use it — not just look at it.',
    ],
  },
  {
    id: 'project5',
    title: 'Courtline',
    img: '/project5/project5.webp',
    link: '/projects/project5',
    date: '2026',
    company: 'Personal',
    liveLink: 'https://courtline.malikfajar.me',
    primary: '#000000',
    accentColor: '#f0f4f1',
    secondary: '#FAFAFA',
    fillColor: '#f2f2f2',
    menuColor: '#FFD54F',
    menuFontColor: '#000000',
    fluidColor: '#002AB0',
    images: [
      {
        src: '/project5/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/3.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project5/4.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project5/5.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/6.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/7.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/8.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/9.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project5/10.webp',
        tag: 'medium',
        isRight: false,
      },
    ],
    desc: [
      'Courtline is a visual experiment: animation, interaction, and a modern composition pushed until the interface feels alive.',
      'A playground for motion, transitions, and pacing on the web — the same curiosity that drives this portfolio.',
    ],
  },
  {
    id: 'project1',
    title: 'JKN BPJS',
    img: '/project1/project1.webp',
    link: '/projects/project1',
    date: '2026',
    company: 'Hackathon',
    liveLink: 'https://jkn-bpjs-projek.malikfajar.my.id',
    primary: '#000000',
    accentColor: '#f0f4f1',
    secondary: '#F9F9F9',
    fillColor: '#ebfaf8',
    menuColor: '#00a8c1',
    menuFontColor: '#f0f4f1',
    fluidColor: '#FF573E',
    images: [
      {
        src: '/project1/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/2.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project1/7.webp',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project1/5.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/6.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/8.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/3.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project1/4.webp',
        tag: 'small',
        isRight: true,
      },
    ],
    desc: [
      'A hackathon app for JKN BPJS: healthcare services behind a calmer, faster interface that people can actually navigate.',
      'Designed to reduce friction — fewer steps, clearer hierarchy, and an experience that respects the user under pressure.',
    ],
  },
  {
    id: 'project2',
    title: 'EduVerse',
    img: '/project2/project2.webp',
    link: '/projects/project2',
    date: '2026',
    company: 'Personal',
    liveLink: 'https://eduverse.malikfajar.my.id',
    primary: '#0e0063',
    accentColor: '#f0f4f1',
    secondary: '#fbfbfc',
    fillColor: '#e1e1f9',
    menuColor: '#170053',
    menuFontColor: '#f0f4f1',
    fluidColor: '#E8FFC8',
    images: [
      {
        src: '/project2/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project2/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project2/3.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'EduVerse is an education site with a brutalist-modern face: learning materials that stay easy to reach without flattening the visual character.',
      'Built to prove that function and attitude can share the same page.',
    ],
  },
];
export default projects;
